### ISSUE TITLE
Doctors can't see his profile details under "More".. "More" is not visible if logined as doctor

### ISSUE THREAD

**Issue by purushotamk** [prakma/hmp-web#1]
1. login as doctor and go to own profile page
2. It does not display or provide option to expand (like More..) to see details about Awards/Recoginization, Membership, Experience etc...
3. These (Awards/Recoginization, Membership, Experience etc...) could be seen by patient by clicking more

I think we could remove more/less and let it to display full profile by scrolling

**Comment by prakma** [comment]
fixed it sometime back. please check and close

**Comment by purushotamk** [comment]
Fixed
