### ISSUE TITLE
Got error "api access not authorized : referrer "https:/remedysquare.com is not allowed(000) when entered consultation room for both doctor and patient  or your browser is not webRTC compatible

### ISSUE THREAD

**Issue by purushotamk** [prakma/hmp-web#10]
Got error "api access not authorized : referrer "https:/remedysquare.com is not allowed(000) when entered consultation room for both doctor and patient

It is same behavior firefox and chrome

It says your browser is not webRTC compatible on safari

**Comment by prakma** [comment]
this should work now.

**Comment by prakma** [comment]
please close this if it works now.

**Comment by purushotamk** [comment]
checked and it is fixed
