### ISSUE TITLE
Chat with patient not working from consultation room

### ISSUE THREAD

**Issue by purushotamk** [prakma/hmp-web#11]
Does patient has option to chat with doctor?

**Comment by prakma** [comment]
I was thinking of adding that functionality...but it is not implemented. Maybe we should just take it out from UI as well for now, and come back to it later

**Comment by purushotamk** [comment]
I agree.. let us take out and we will take up it latter

**Comment by prakma** [comment]
removed the chat from the UI

**Comment by purushotamk** [comment]
Fixed
